### ISSUE TITLE
highlighting not working

### ISSUE THREAD

**Issue by gandhiShepard** [connorlay/tree-sitter-eex#10]
Highlights work as expected in .ex files, but they do not work on .eex files. I see that the filetype of `eelixir` is being used on .eex files.

if I `:set filetype=eex`, then the eex highlights work, but the html highlights do not.
if I `:set filetype=eelixir.html`, then the html highlights work, but the eex highlights do not.

Should I be setting a different file type? Much respect!

![Screenshot 2023-01-04 at 12 50 08 PM](https://user-images.githubusercontent.com/8546059/210627949-775053fb-e949-47e3-b6e2-cb71eed175dc.jpg)

**Comment by torifaye** [comment]
also running into this issue, have you figured out a workaround or root cause by chance?

**Comment by connorlay** [comment]
This repository does not contain anything specific to support Neovim. I suggest opening an issue in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) 🙂
